name: test_table_one
fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one'
description: testing reverse
tableType: Regular
columns:
  - name: is_for_sale
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.is_for_sale'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: is_master_product
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.is_master_product'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: is_active
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.is_active'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: is_renewable
    dataType: BOOLEAN
    dataLength: 1
    dataTypeDisplay: boolean
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.is_renewable'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: line_of_business
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: character varying(256)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.line_of_business'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: product_id
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: character varying(256)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.product_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: master_product_original_name
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: character varying(256)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.master_product_original_name'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: module_id
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: character varying(256)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.module_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: type_name
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: character varying(256)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.type_name'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: sub_type
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: character varying(256)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.sub_type'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: full_name
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: character varying(256)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.full_name'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: item_id
    dataType: VARCHAR
    dataLength: 256
    dataTypeDisplay: character varying(256)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.item_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: master_product_id
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: bigint
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.master_product_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: department_id
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: bigint
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.department_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: income_account_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.income_account_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: item_frequency_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.item_frequency_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: class_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.class_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: subsector_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.subsector_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: level_2_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.level_2_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: level_1_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.level_1_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: master_product_reporting_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.master_product_reporting_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: license_type_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.license_type_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: delivery_method_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.delivery_method_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: item_type_id
    dataType: DOUBLE
    dataLength: 1
    dataTypeDisplay: double precision
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.item_type_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: date_last_modified
    dataType: TIMESTAMP
    dataLength: 1
    dataTypeDisplay: timestamp with time zone
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.test_table_one.date_last_modified'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners:
  - id: fb8e44c9-b9c5-45bc-9691-b3343b5d5b7c
    type: user
    name: 23saints23
    fullyQualifiedName: 23saints23
    displayName: 23saints23
    deleted: false
  - id: 1fec0260-5ad5-4d56-9d2c-48104368bc10
    type: user
    name: sonika.s
    fullyQualifiedName: '"sonika.s"'
    displayName: sonika.s
    deleted: false
databaseSchema:
  id: bc547047-05f7-4746-9ce3-7388fd77ad8c
  type: databaseSchema
  name: dbt_jaffle
  fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle'
  displayName: dbt_jaffle
  deleted: false
database:
  id: 0a7d8aae-ea17-4dc4-96d0-2d8979ac5963
  type: database
  name: dev
  fullyQualifiedName: '"1.8.7-test".dev'
  displayName: dev
  deleted: false
service:
  id: b27756b3-8d33-47c6-b2c5-bd2e1fa35831
  type: databaseService
  name: 1.8.7-test
  fullyQualifiedName: '"1.8.7-test"'
  description: ""
  displayName: 1.8.7-test
  deleted: false
serviceType: Redshift
tags: []
joins:
  startDate: 2026-01-21
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 8358ddc6ad929275cdab137afc86331d
processedLineage: false
entityStatus: Unprocessed
