name: new_view_1
fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.new_view_1'
tableType: View
columns:
  - name: customer_id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.new_view_1.customer_id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: customer_lifetime_value
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: bigint
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.new_view_1.customer_lifetime_value'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: first_name
    dataType: VARCHAR
    dataLength: 10
    dataTypeDisplay: character varying(10)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.new_view_1.first_name'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: first_order
    dataType: DATE
    dataLength: 1
    dataTypeDisplay: date
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.new_view_1.first_order'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: last_name
    dataType: VARCHAR
    dataLength: 2
    dataTypeDisplay: character varying(2)
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.new_view_1.last_name'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: most_recent_order
    dataType: DATE
    dataLength: 1
    dataTypeDisplay: date
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.new_view_1.most_recent_order'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: number_of_orders
    dataType: BIGINT
    dataLength: 1
    dataTypeDisplay: bigint
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.new_view_1.number_of_orders'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners:
  - id: fb8e44c9-b9c5-45bc-9691-b3343b5d5b7c
    type: user
    name: 23saints23
    fullyQualifiedName: 23saints23
    displayName: 23saints23
    deleted: false
  - id: 1fec0260-5ad5-4d56-9d2c-48104368bc10
    type: user
    name: sonika.s
    fullyQualifiedName: '"sonika.s"'
    displayName: sonika.s
    deleted: false
databaseSchema:
  id: bc547047-05f7-4746-9ce3-7388fd77ad8c
  type: databaseSchema
  name: dbt_jaffle
  fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle'
  displayName: dbt_jaffle
  deleted: false
database:
  id: 0a7d8aae-ea17-4dc4-96d0-2d8979ac5963
  type: database
  name: dev
  fullyQualifiedName: '"1.8.7-test".dev'
  displayName: dev
  deleted: false
service:
  id: b27756b3-8d33-47c6-b2c5-bd2e1fa35831
  type: databaseService
  name: 1.8.7-test
  fullyQualifiedName: '"1.8.7-test"'
  description: ""
  displayName: 1.8.7-test
  deleted: false
serviceType: Redshift
schemaDefinition: create view dbt_jaffle.new_view_1 as select * from dbt_jaffle.customers_model
  cm ;
tags: []
joins:
  startDate: 2026-01-21
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 373b6a64699960e6d6f02c30f3fe1e95
processedLineage: false
entityStatus: Unprocessed
