name: geometry_table
fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.geometry_table'
description: Geometry test changed here
tableType: Regular
columns:
  - name: id
    dataType: INT
    dataLength: 1
    dataTypeDisplay: integer
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.geometry_table.id'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: geo_col
    dataType: GEOMETRY
    dataLength: 1
    dataTypeDisplay: geometry
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.geometry_table.geo_col'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: hll
    dataType: HLLSKETCH
    dataLength: 1
    dataTypeDisplay: hllsketch
    fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle.geometry_table.hll'
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners:
  - id: fb8e44c9-b9c5-45bc-9691-b3343b5d5b7c
    type: user
    name: 23saints23
    fullyQualifiedName: 23saints23
    displayName: 23saints23
    deleted: false
  - id: 1fec0260-5ad5-4d56-9d2c-48104368bc10
    type: user
    name: sonika.s
    fullyQualifiedName: '"sonika.s"'
    displayName: sonika.s
    deleted: false
databaseSchema:
  id: bc547047-05f7-4746-9ce3-7388fd77ad8c
  type: databaseSchema
  name: dbt_jaffle
  fullyQualifiedName: '"1.8.7-test".dev.dbt_jaffle'
  displayName: dbt_jaffle
  deleted: false
database:
  id: 0a7d8aae-ea17-4dc4-96d0-2d8979ac5963
  type: database
  name: dev
  fullyQualifiedName: '"1.8.7-test".dev'
  displayName: dev
  deleted: false
service:
  id: b27756b3-8d33-47c6-b2c5-bd2e1fa35831
  type: databaseService
  name: 1.8.7-test
  fullyQualifiedName: '"1.8.7-test"'
  description: ""
  displayName: 1.8.7-test
  deleted: false
serviceType: Redshift
tags: []
joins:
  startDate: 2026-01-21
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 4dd80b560a3f706547de981092e16d09
processedLineage: false
entityStatus: Unprocessed
