name: products_json
fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json
tableType: External
columns:
  - name: product_id
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json.product_id
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: name
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json.name
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: category
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json.category
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: subcategory
    dataType: STRING
    dataLength: 1
    dataTypeDisplay: string
    fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json.subcategory
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: price
    dataType: FLOAT
    dataLength: 1
    dataTypeDisplay: double
    fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json.price
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: cost
    dataType: FLOAT
    dataLength: 1
    dataTypeDisplay: double
    fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json.cost
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: margin_percent
    dataType: FLOAT
    dataLength: 1
    dataTypeDisplay: double
    fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json.margin_percent
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
  - name: stock_quantity
    dataType: INT
    dataLength: 1
    dataTypeDisplay: int
    fullyQualifiedName: athena pablo test.default.ecommerce_multiformat.products_json.stock_quantity
    tags: []
    constraint: "NULL"
    children: []
    customMetrics: []
tableConstraints: []
owners: []
databaseSchema:
  id: 42ab0804-898c-4c9b-bed5-00d0ed4e52ea
  type: databaseSchema
  name: ecommerce_multiformat
  fullyQualifiedName: athena pablo test.default.ecommerce_multiformat
  description: Multi-format schema for compatibility testing
  displayName: ecommerce_multiformat
  deleted: false
database:
  id: 81546c5f-458f-4fb1-abc1-fa271fa96c1a
  type: database
  name: default
  fullyQualifiedName: athena pablo test.default
  displayName: default
  deleted: false
service:
  id: 7b307983-8500-47ee-b04d-68c2e64c278e
  type: databaseService
  name: athena pablo test
  fullyQualifiedName: athena pablo test
  description: ""
  displayName: athena pablo test
  deleted: false
serviceType: Athena
locationPath: s3://collate-athena-654654515160/data/ecommerce/multiformat/json/products
tags: []
joins:
  startDate: 2026-01-18
  dayCount: 30
  columnJoins: []
  directTableJoins: []
customMetrics: []
domains: []
dataProducts: []
sourceHash: 84de563099ecc8901d5b92ff68e75f66
processedLineage: false
entityStatus: Unprocessed
